### ISSUE TITLE
How to can I start this? 

### ISSUE THREAD

**Issue by nerdchanii** [siner308/ubuntu1604#1]
# Question for Using

 I don't know How to start this. 
What user needs for using this?

Can I know more details?

**Comment by siner308** [comment]
You need to install docker and docker-compose first

1. install docker
Visit [this website](https://docs.docker.com/get-docker/) and install docker what your os supports.

If you are using MacOS, you can install docker desktop.
If you want to use docker without `sudo` you can run command `sudo usermod -aG docker $USER` in unix system after install docker.

2. install docker compose
VIsit [this page](https://docs.docker.com/compose/install/) and install docker compose.
If you are using MacOS, docker compose is installed with docker desktop at once.

Now you can use docker and docker-compose

I'm writing next step right below.

**Comment by siner308** [comment]
here is full steps after you install docker and docker compose.

```bash
$ git clone https://github.com/siner308/ubuntu1604
$ cd ubuntu1604
$ docker-compose up -d  # execute container in background
$ docker ps  # check ubuntu is running
```

**-d** option after `docker-compose up` will docker can be run background.

```bash
$ docker exec -it ubuntu1604 bash  # you can access into docker with bash
```

**Comment by nerdchanii** [comment]
Thanks, Nice guide!
